name: Test for Secrets Access

description: Test for secrets access. NEVER run this with a secret other than the "TEST_REPOSITORY_SECRET"

on:
  workflow_dispatch:
  pull_request_target:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - reopened

env:
  TEST_SECRET: ${{ secrets.TEST_REPOSITORY_SECRET }}

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read
breaks
jobs:
  test-for-secret-access:
    runs-on: ubuntu-latest
    steps:
      name: Test for Secret Access
      run: |
        echo "Secret is: ${TEST_SECRET}"