name: Test for Secrets Access

description: Test for secrets access. NEVER run this with a secret other than the "TEST_REPOSITORY_SECRET"

on:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
  workflow_dispatch:


env:
  TEST_SECRET: ${{ secrets.TEST_REPOSITORY_SECRET }}

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  test-for-secret-access:
    runs-on: ubuntu-latest
    steps:
      - name: Test for Secret Access
        run: |
          echo "Secret (base64-encoded): $(echo "$TEST_SECRET" | base64)"

