name: Update Repo Custom Properties

description: Updates the repo custom properties as defined in the provided governance repo, repo-properties.yaml file.

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  update-properties:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
          ref: ${{ steps.validate.outputs.build-tag }}
          token: ${{ secrets.GH_CUSTOM_PROPERTIES_TOKEN }}

      - name: List current checkout
        run: |
          echo "Cloned current repo"
          echo "Running pwd now"
          pwd
          echo "Running ls now"
          ls -la

      - uses: andrewb1269hg/update-custom-props@v0.0.2
        with:
          governance-repo-url: 'https://github.com/org-andrewb1269hg/my-governance-repo.git'
          token: ${{ secrets.GH_CUSTOM_PROPERTIES_TOKEN }}
