name: Update Repo Custom Properties

description: Updates the repo custom properties as defined in the provided governance repo, repo-properties.yaml file.

on:
  workflow_dispatch:

jobs:
  update-properties:
    runs-on: ubuntu-latest
    steps:
      - uses: andrewb1269hg/update-custom-props@3-create-action-to-update-custom-properties-in-a-repo
        with:
          governance-repo-url: 'https://github.com/org-andrewb1269hg/my-governance-repo.git'
